README.md

README.md: add features, requirements and usage example

---

test/conftest.py
test/test_storage.py

Add the first tests to the projects. They have been adapted from similar tests in pghoard.

Add first tests

---

.github/workflows/publish-pypi.yaml

```
git checkout main
git pull
git tag -a releases/1.0.0 -m 'Version 1.0.0'
git push --tags
```

packaging: only push tags named releases/

---

.github/workflows/sphinx.yml
docs/about.rst
docs/index.rst

Add GitHub pages auto build for #5.

sphinx: add GitHub workflow

---

.github/workflows/build.yml
.style.yapf
test/conftest.py
test/test_storage.py

Enable validate style on CI.
The configuration is the same from pghoard.
Next step:
- add black ...

ci: enable validate style

---

rohmu/__init__.py

Super small PR that introduces additional typing for the config object

typing for init

---

rohmu/object_storage/google.py

The API is dynamically generated from an specification, i.e. there isn't really a python code to navigate to with jump-to-definition. This makes it a little bit harder to figure out what arguments are available and what is the return type. To make other's life easier, I added links to the relevant documentation.

google: added links to documentation

---

pyproject.toml
requirements.dev.txt
rohmu/notifier/__init__.py
rohmu/notifier/http.py
rohmu/notifier/interface.py
rohmu/notifier/logger.py
rohmu/notifier/null.py
test/notifier/test_http.py
test/notifier/test_interface.py
test/notifier/test_logger.py
test/notifier/test_null.py

Alternative implementation of https://github.com/aiven/rohmu/pull/59 using composition instead of inheritance.
This only adds the notifier interface and a few implementations, it does not yet integreate the code in the drivers (will be done on a follow up, split to make reviewing easier)

Notifier implementation

---

Makefile
rohmu/__init__.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py

~Merge/Review after https://github.com/aiven/rohmu/pull/66~
Add support for the notifier to each driver

Integrate notifier with drivers

---

rohmu/version.py

Bump version number to 1.0.5 for a new release.

Version 1.0.5

---

rohmu/version.py

Bump version to 1.0.6.
It is the only correct way.

Version 1.0.6

---

rohmu/object_storage/google.py

the size is key missing and the documentation mentions the key to be present but in practice that doesnot seem to be the case, sometimes.
Try and avoid throwing an exception in such cases

handle missing size key in result

---

requirements.dev.txt
rohmu/__init__.py
rohmu/models.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/test_from_model.py

these models are not yet directly used in the classes but act as way to validate/annotate the inputs expected by these transfer classes

pydantic models for transfer objects

---

rohmu/common/models.py
rohmu/common/statsd.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/test_object_storage_s3.py

commit 2 and 3 are essentially the same. commit 3's approach feels less intrusive. 
Commit messages have more info

metrics for s3

---

rohmu/object_storage/local.py
test/test_storage.py

- add support for hashes in local storage (useful when testing against it, as most storages report it)
- add primitive delete tests

Miscellaneous fixes

---

rohmu/object_storage/s3.py

Adds support for virtual host addressing to S3Transfer.

s3: support virtual host addressing

---

README.rst
docs/about.rst
docs/conf.py
docs/development.rst
docs/index.rst
docs/usage.rst

This bootstraps docs from README.rst and CONTRIBUTING.md

docs: bootstrap docs

---

rohmu/object_storage/s3.py

object_storage,s3: fix head_bucket call according to docs.
Previous method of error handling was wrong.

object_storage,s3: fix head_bucket call according to docs

---

make_release.py
rohmu/version.py

* Ensure tags are signed
* push tag and new commit together (this is assuming we want the "Bump to version" commits which are in the tags on master)
This also includes a missing commit that is in the pushed 2.0.1 release but I could not push to master because I do not have permission.

Sign tag and push commit _and_ tag together in make_release.py

---

rohmu/factory.py

* we are referencing this error in at least one place
Will be resolved by: https://github.com/Aiven-Open/pghoard/pull/606
As shown https://github.com/Aiven-Open/pghoard/pull/606#discussion_r1356778533 we use the commit hash provided in this PR to test it.

Keep backwards compatibility with InvalidConfigurationError

---

rohmu/delta/common.py
rohmu/delta/snapshot.py
test/delta/test_snapshot.py

Updated the snapshot method to include a progress_callback for better tracking of operation. This allows for real-time progress tracking during snapshot operations, improving logging and debuggability for delta backup.

feat: Add progress_callback to snapshot method

---

.github/workflows/build.yml
pyproject.toml

Ensures the library is tested with the newer stable python version.

Ensure the library is compatible with Python 3.12

---

rohmu/object_storage/azure.py
test/object_storage/test_azure.py

Fix error handling to catch 416 response from Azure with additional check for blob size to map it to empty object.
The check for 416 HTTP status code already existed under wrong exception catch and only needed to be moved to under correct exception.
As the error only indicates that the range is invalid, an additional check for the blob size is added.

Fix Azure empty object download

---

rohmu/object_storage/google.py

Resolves: Errors of ServerNotFound wihle executing a request.

google: retry on httplib2.ServerNotFoundError

---

rohmu/errors.py
rohmu/object_storage/s3.py
test/object_storage/test_s3.py

Resume S3 download if it fails with a timeout.

Support range resume on s3 get object timeout

---

rohmu/object_storage/config.py
rohmu/object_storage/s3.py
test/object_storage/test_s3.py

maximum number of parts per upload for s3 compatible api is 10_000.
make sure we respect that and if needed we increase the chunk size to avoid starting a multipart upload with number of chunks (parts) that we already know is not valid.
chunk size is increased by multiplying previous size by 2 until we reach maximum chunk size.

s3: respect max num of parts per upload
