.github/workflows/publish-pypi.yaml

Was copy-pasted from https://github.com/aiven/aiven-client/blob/main/.github/workflows/publish-pypi.yaml
Decided to use the lowest supported python version, but did not find any for or against it.

Publish to PyPI with GitHub Action

---

.github/workflows/build.yml
.pylintrc
Makefile
codecov.yml
mypy.ini
requirements.dev.txt
test/conftest.py
test/test_storage.py

Adding ci pipeline to run lint and test on main and pull requests. Also, uploading coverage to codecov (todo: after running tests). Based on pghoard (using same version) to avoid change a lot of files in this initial step.
Resolves: https://github.com/aiven/rohmu/issues/2 and https://github.com/aiven/rohmu/issues/14

rohmu add ci pipeline

---

conf.py

sphinx build fails because of missing `docs/conf.py`.

docs: add conf.py

---

rohmu.spec
rohmu/object_storage/azure.py

AzureTransfer currently only authenticates using a Service Account name and secret, which does not allow for granular permissions. Adding SAS token authentication to allow more restrictive permissions to be applied to the Storage Account where backups are stored.
Had an existing [PR](https://github.com/aiven/pghoard/pull/509) for this in pghoard, but recreating it since the rohmu project is being moved out of pghoard.
Having the option to authenticate via SAS token (see [Azure docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview) for more info) provides more flexibility to decide which permissions are granted to an Azure service, and can be easily revoked if the token ever becomes compromised. This is better than using the Service Account credentials, since …

Support azure authentication with SAS token

---

rohmu/object_storage/s3.py

forwards timeouts to the botocore lib for better control, otherwise the process just hangs

allow passing timeouts to s3 wrapper

---

rohmu/object_storage/azure.py
rohmu/object_storage/google.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py

This is a biggish change, I have it in a separate PR so that reviewing can be easier.
It just makes sure the value `key` is no longer shadowed, so it consistently name the formatted key `path`. The original value of `key` will be used by the notifier interface (an alternative implementation of #59)

No longer shadow the argument key

---

.github/workflows/build.yml
.github/workflows/publish-pypi.yaml
README.rst
setup.cfg

As the tile says, 3.6 has reached EOL last year

drop support for Python 3.6 [EOL 23/Dec/2021]

---

.github/workflows/build.yml
.github/workflows/publish-pypi.yaml

The value `3.10` is parsed as an integer and the right most zero is dropped. The effect is that GH CI tried to run the build using python 3.1 instead of 3.10. The fix is to use strings to define the version instead of numbers.

build: fix python version on yaml

---

rohmu/object_storage/azure.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/test_object_storage_azure.py
test/test_object_storage_sftp.py
test/test_object_storage_swift.py

For Azure, Swift and SFTP object storages, the attempt to get object size for completion notifications was incorrect, calling `os.path.getsize()` with a file-like object, instead of a path.
Given that the object to store may not be a file on disk, that can be seeked or `stat()`ed, we need some other way to obtain the number of bytes.
For these storages, the store call doesn't seem to return the object size in a convenient way, so make use of the progress callback we implement for object storage backends. That gives us the number of bytes transferred, that we can then pass on to notifier.
For tests, start with these three backends that seemed to have been broken by #67. Some libraries used by them are not in our requirements.dev.txt, so settle for mocking those imports.
Looks to fix a few …

notifier: fix notifications for some storage types, add tests

---

rohmu/object_storage/s3.py
test/test_object_storage_google.py
test/test_object_storage_local.py
test/test_object_storage_s3.py

Add some tests for the object storage types that didn't have them yet. so that the recently added object storage notification feature gets better test coverage.

Add some unit tests for object storages that were lacking them

---

rohmu/object_storage/swift.py
test/test_object_storage_swift.py

Listing all keys on root level for Swift requires passing `""` as a key.
Currently, in swift `iter_key` converts empty key (`""`) to `"/"`, which makes Swift return empty list of results even when there should be results.
This change fixes the issue.
Because it is the simpliest way to fix this issue.

swift: fix iter_key on empty string

---

rohmu/notifier/http.py
rohmu/notifier/interface.py
rohmu/notifier/logger.py
rohmu/notifier/null.py
rohmu/object_storage/azure.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/notifier/test_http.py
test/notifier/test_interface.py
test/notifier/test_logger.py
test/notifier/test_null.py
test/test_object_storage_azure.py
test/test_object_storage_google.py
test/test_object_storage_local.py
test/test_object_storage_s3.py
test/test_object_storage_sftp.py
test/test_object_storage_swift.py

this helps notification consuming side not have query it if needed.

pass object metadata also via the http notifier

---

rohmu/notifier/http.py

this gives the receiving side more time to recover fromr a restart

notfier: bump retry times and backup_off for http notifer

---

rohmu/notifier/http.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/test_object_storage_azure.py
test/test_object_storage_google.py
test/test_object_storage_local.py
test/test_object_storage_s3.py
test/test_object_storage_sftp.py
test/test_object_storage_swift.py

this is needed because metdata can contain complex objects like datetime
An easier way to fix this would be to move sanitize_metadata out of baseclass to utils and directly call it from notifer, but in case of azure the hypen(-) in keys needs to be replaced with underscore (_). and notifer has no idea what storage driver was is use and if hyphen replacement should be done.

notifier: sanitize metadata before trying to json dump

---

rohmu/object_storage/s3.py

Session token needs to be provided when using federated user. This allows using temporary tokens with Rohmu instead of permanent user credentials.
Allows using token obtained from GetFederationToken with Rohmu
In some cases it is preferred to use temporary tokens instead of
permanent user credentials when interacting with the object storage.
Without being able to set the session token this is not possible.

s3: Allow passing AWS session token

---

.github/workflows/build.yml
.github/workflows/publish-pypi.yaml
.github/workflows/sphinx.yml
requirements.dev.txt
rohmu.spec
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
rohmu/rohmufile.py

While some methods already support a progress metric being passed to them, some do not. This makes it difficult to transition upstream projects to rely on progress-based metrics and alerting.
This PR enhances `rohmufile` to inject an argument - the number of bytes transmitted - to its callback, while maintaining backwards-compatibility. It also adds progress callback support to `store_file_from_disk`, which previously did not support it, and allows more implementations to invoke the progress callbacks in more situations. (For example, the `s3` backend now provides progress during a multi-part file upload, which is very common)

Provide consistent progress metric callbacks

---

rohmu/object_storage/azure.py
rohmu/object_storage/s3.py

Two imports added an additional dependency to rohmu which is not justified. 
While type-checking is very good practice in general, requiring extra downstream packages should not be required for a minor/point release.

Remove problematic S3 mypy-related imports

---

.github/workflows/publish-pypi.yaml

Using the current version of github's checkout action, tags are not properly synced, even when `fetch-depth: 0` is present.
Explicitly fetch the tag references to ensure the annotated tag check succeeds. Without this change, the object type of the reference is simply `commit`, and not `tag`.

Fix the pypi publisher

---

rohmu/object_storage/google.py
test/test_object_storage_google.py

somestimes these files are really small (<1MB) sometimes just a few bytes. These get reported as 5MB over even more.
with these (stored_file_from_memory, store_file_from_string) calls it is trivial to get the actual size of data, this helps steer not too far away from the actual sizes.
this might lead to undercounting in case of retries but with such small sizes this should be fine

improve google stats reporting

---

rohmu/common/models.py
rohmu/common/statsd.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
rohmu/rohmufile.py
test/test_object_storage_google.py
test/test_object_storage_local.py
test/test_object_storage_s3.py
test/test_object_storage_sftp.py
test/test_storage.py

- Add get_contents_to_file/string to base class
(No API change, just implementation simpliciy)
Ultimately only get_contents_to_fileobj is the interesting one (if we don't implement proper parallel multipart download anyway), and the other two can just use that.
- Add store_file_from_memory, store_file_from_disk to base class
NOTE: Backward incompatible API change - require keyword arguments also in store_file_from_disk (all Aiven code is fine with it, and we want this going forward)
NOTE: Handling of 'metadata' varied by functions (in some it was keyword argument, in others not); made it non-keyword third argument in all 3 store variants. (This is backwards compatible, as restrictions were just loosened.)
- operation tracking changes/fixes
- documented the operations somewhat
- added …

object_storage: API + operation changes

---

rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py

Fixes a bug introduced in https://github.com/aiven/rohmu/pull/101
As it turns out, delete_keys did not really work correctly (and therefore broke also delete_tree). No mypy or test coverage unfortunately. Added mypy coverage, and it is tested elsewhere that the code actually works (but teardown failures were ignored during previous PR work).
While adding proper tests would have been nice too, adding typing + testing elsewhere is hopefully sufficient for now (we have to solve the test credential handling problem first).

Fix S3 delete_keys and add typing

---

requirements.dev.txt
rohmu/object_storage/s3.py
test/test_object_storage_s3.py

Apparently the fixed code wasn't right either but the tests I ran on it outside were insufficient (they did not notice delete failures due to prefix being omitted as we don't parse the delete_keys response).
Now actually added unit tests for the s3 delete_key* and also added prefix parameter to s3 storage tests in general to ensure it is passed along to the API calls that we check. In the future better unit tests would be nice but at least these enforce that the prefix is not dropped (for the covered cases) in the future.

Fix S3 delete_keys harder

---

rohmu/object_storage/s3.py

There are cases where the list_objects_v2 api returns objects that are not actually present in s3. This cause an error to happen. We should skip these "files"
Skip file that fail the head_object api

Skip file when key is not found in s3.

---

rohmu/errors.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
rohmu/util.py
test/test_object_storage_azure.py
test/test_object_storage_google.py
test/test_object_storage_local.py
test/test_object_storage_s3.py
test/test_storage.py
test/test_util.py

It allows providing a byte_range for the method `get_contents_to_fileobj` of transfer classes.
Some APIs provide built-in support for this change, others do not.
For the Google implementation:
This PR uses a patched version of a googleapiclient class to add support to the byte_ranges.
I've looked a bit in the alternative of moving to google's cloud libraries, but to me it sounds like a lot of work and I don't see a simple way to use those just for the use-case of adding byte-range support so it would mean a rewrite of the whole google implementation from what I see.
BTW: I started from mst-dev branch but I rebased it on `main` fixing the conflicts, that's why there are some fingon's commits.

Implement byte_range download

---

requirements.dev.txt
rohmu.spec
rohmu/object_storage/s3.py

Remove the boto3 dependency, there are no functional changes, 
The boto3 dependency is not needed, since we also use the botocore dependency. Additionally the boto3 dependency is more likely to result in dependency mismatches.

object_storage: remove boto3 dependency

---

.github/workflows/build.yml
.github/workflows/publish-pypi.yaml
.gitignore
README.rst
rohmu/errors.py
rohmu/object_storage/base.py
rohmu/object_storage/local.py
rohmu/transfer_pool.py
setup.cfg
test/test_transfer_pool.py

Implements a transfer-pool API that allows multiple user threads to safely share rohmu transfer objects.
A new `rohmu.transfer_pool` module was added which defines `TransferPool` class. The class provides 2 methods to get a transfer object:
* The `with_transfer(storage_config)` method can be used as context manager
* The `get_transfer(storage_config)` method can be used to obtain a transfer object. This is a proxy that will act exactly as the normal transfer and includes a `return_to_pool` method which MUST be called by the user once they are done. All interactions after this call are prevented.
The module also provides a default pool instance which can be used via the `with_transfer` and `get_transfer` global functions.
Various object storage backends are not thread-safe, so users would …

implement transfer pooling

---

rohmu/version.py

Bumping to version 1.1.0
Somehow main is at 1.0.9 but PyPI has version 1.0.10 available... I guess in the last release the tag was pushed and the branch deleted instead of being merged into main?
I need a new version so that we can update robjecter dependency on rohmu to use new transfer pool.
After merging this to main I will push the tag to trigger the new release.

Bump to version 1.1.0

---

rohmu/object_storage/local.py
rohmu/typing.py
test/test_object_storage_local.py

The local driver now considers the hash of the file as optional metadata.
If a user used a previous version of rohmu to save some files, those will not have the hash in the metadata stored. If they used the new rohmu version to list the files it will barf at the missing md5.
We could compute it on the fly but for now simply ignore it if it is missing.

local: fix broken backward compatibility for files without md5 metadata

---

rohmu/version.py

Bump rohmu to 1.1.1. Since 1.1.0 broke backward compatibility with older versions due to the md5 hash and we have merged the fix it's time to have a new public release to publish the fix on PyPI.
After merging this I will push the release tag.

Bump to version 1.1.1

---

.github/workflows/build.yml

Build rohmu also for python3.11
We need to install `libsnappy-dev` because otherwise `python-snappy` won't install on python3.11

Add python3.11 pipeline to the build

---

rohmu/encryptor.py
rohmu/filewrap.py
rohmu/snappyfile.py
rohmu/typing.py
rohmu/zstdfile.py

This reverts commit 5c058b759d64fb08919d1f2034e4ae647d4d0e16.
It broke code using older typing_extensions versions.
Instead we use a couple of `type: ignore` comments to stop mypy from complaining.

Revert "typing: fix liskov principle errors"

---

rohmu/object_storage/s3.py
test/test_from_model.py

Fix a bug when `rohmu.get_transfer()` is passing addressing style enum values from Config to create S3Transfer object. Also improves `test_from_model` to find similar issues.

s3: fix a bug handling addressing style enum value

---

rohmu/object_storage/s3.py
test/test_object_storage_s3.py

HTTP specs specify = as separator between unit and the ranges, not space. We already use the correct syntax for multipart.

rohmu: fix Range header syntax for S3 implementation

---

.github/workflows/build.yml
docs/conf.py

For now importing `rohmu.version` would also require importing other `rohmu` dependencies, this removes the import in `docs/conf.py`, and also adds a github action that runs sphinx-build on pull requests (without pushing the generated docs to `gh-pages`).

docs: remove version import from conf.py for now

---

rohmu/errors.py
rohmu/object_storage/base.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/typing.py
rohmu/util.py
test/test_object_storage_local.py
test/test_object_storage_s3.py
test/test_util.py

Alternative version of https://github.com/aiven/rohmu/pull/128
Simplifies API (no resume) and avoids an extra class.

concurrent multipart support for transfer

---

rohmu/common/models.py
rohmu/common/statsd.py
rohmu/common/strenum.py
rohmu/object_storage/base.py
rohmu/object_storage/config.py

- common: introduce StrEnum class
- object_storage: introduce `StorageDriver` enum
- object_storage: hide object storage config secrets in representation
- object_storage: make object storage config field types more precise
- object_storage: split object storage config models
To allow downstream use rohmu configs instead of code duplication. See commit messages for more info.

object_storage: config models improvements

---

rohmu/object_storage/config.py

This reverts commit 73fb83b6
This checks that the file or folder exists at the time the config object is created,
it's perfectly valid for the file or folder to not exist when the object is created
and sometimes impossible for that file or folder to exist:
The config may be created in a different environment from where the config
will be used in the end (different chroot, container or server).
Using the object type to validate a property that is actually not part of the
object but part of the external environment is flaky anyway: the environment
will change outside of the control of the object and the property validated
when the object was constructed will become false while the code using
the object will believe that property is still true.

Revert "object_storage: make object storage config field types more precise

---

rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
test/object_storage/test_object_storage.py

This adds support for copy of multiple files across different buckets,
for now only if the two buckets are on the same provider.
This enables copying data from bucket to bucket without storing it locally.

Add support for bucket to bucket copy

---

.gitignore
setup.cfg

Add a `py.typed` marker so that type hints can be used by mypy in projects that use this library.

Add py.typed marker

---

mypy.ini
rohmu/object_storage/config.py
rohmu/object_storage/s3.py
test/object_storage/test_s3.py

Allow passing a certificate to the s3 client.  This is needed for easy interop with MinIO.
Note that this is an option for botocore https://github.com/boto/botocore/blob/develop/botocore/session.py#L874

s3: allow passing cert_path to S3Transfer

---

.github/workflows/build.yml
rohmu/__init__.py
rohmu/common/models.py
rohmu/common/strenum.py
rohmu/factory.py
rohmu/object_storage/base.py
rohmu/object_storage/s3.py
rohmu/transfer_pool.py
setup.cfg
test/common/test_statsd.py
test/object_storage/test_s3.py
test/test_factory.py

Expose the Rohmu config models and add a method `get_transfer_from_model` to get a `transfer` from the pydantic model rather than having to serialize as dict first.  This will help with typing and hopefully eventually reduce the number of copies of these pydantic models currently in our codebase.
Other small improvements:
* Pylance / VSCode doesn't like importing the re-exports in `rohmu/__init__.py`, I think the addition of this `__all__` will change this.
* field `notifier` was confusing on a pydantic model since it is not itself a pydantic class.  Better off just passing this in directly to `BaseTransfer.from_model`
* Since `StorageModelT` is not covariant, it is _not_ the case that, for instance, `S3Transfer < BaseStorage[StorageModel]`.  Mypy correctly claims we cannot make this …

Expose config models

---

Makefile
README.rst
requirements.dev.txt

- Fix all the links.
- Some links were broken.
- Some links were outdated.
- All relative links and images do not work when seen from https://pypi.org/project/rohmu/ or https://aiven-open.github.io/rohmu/
- Add 3 badges.
- Move all the link declarations to the bottom.
- Use an auto-formatter (width=100): `rstfmt`.
This PR is neatly split into commits. You can use that to review manual changes without being polluted by the auto changes from the formatter.

Fix the README.rst

---

requirements.dev.txt
rohmu/atomic_opener.py
rohmu/delta/common.py
rohmu/encryptor.py
rohmu/factory.py
rohmu/filewrap.py
rohmu/object_storage/azure.py
rohmu/object_storage/google.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/rohmufile.py
rohmu/snappyfile.py
rohmu/typing.py
rohmu/util.py
rohmu/zstdfile.py
test/test_atomic_opener.py
test/test_encryptor.py
test/test_rohmufile.py

This fixes some type hint issues that are preventing downstream projects from passing CI.
This contains the following changes:
- `SizeLimitedFile` uses common conventions, types and defaults.
- `_fileobj_name` -> `_obj_name`, as it's not related to files.
- `rohmufile.write_file` only requires `HasRead` for the input file.
- `HasRead`, `HasWrite` use Python conventions, types and defaults.
- `FileLike` uses Python conventions, types and defaults.
- New `HasName`.

Fix type hints

---

rohmu/object_storage/s3.py

The `Access denied on bucket check` warning messages do not add value, at least they are confusing. A missing `s3:ListBucket` permission does not prohibit writing to a bucket.

object_storage: remove access denied warning for s3 buckets

---

rohmu/encryptor.py
test/test_encryptor.py

This change adds variants of the Encryptor and Decryptor classes that use symmetric encryption.

encryptor: add support for symmetric encryption

---

rohmu/object_storage/azure.py
rohmu/object_storage/config.py
test/object_storage/test_azure.py

Adds custom host and port configs to Azure to support custom blob endpoint like Azurite.
Resolves: #163 
Follow similar approach to S3, to set custom host/port.
Moved conn_string construction out of the initialization to be able to test it.

feat: add custom Azure host/port to support custom blob endpoint

---

rohmu/object_storage/azure.py

To maintain compatibility with old versions of the azure blob storage library

fix: keep endpoints from azure for compatibility

---

rohmu/encryptor.py
rohmu/rohmufile.py
test/test_encryptor.py

Loading a key can be very slow, especially since OpenSSL 3.0 started validating the keys:
https://github.com/pyca/cryptography/issues/7236
Even when using the `unsafe_skip_rsa_key_validation` flag, repeatedly loading the keys for each downloaded or uploaded file still takes unnecessary time.
Extend the allowed input types to accept already loaded private and public keys, and also allow these types in the key lookup callback of the `rohmufile` helpers.
Even though the key format is not always `pem` anymore, I kept the original parameter name to avoid backward compatibility issues.

Accept preloaded RSA keys in encryptor/rohmufile

---

rohmu/object_storage/s3.py
test/object_storage/test_s3.py

While reworking the retries the nested-loop was removed and this now
causes only the first part to be uploaded.
This adds a test to ensure that it keeps working and also fixes the
issue.

Fix multipart S3 uploads

---

rohmu/object_storage/config.py
rohmu/object_storage/s3.py
test/test_factory.py

When using the default S3 endpoints, request using dualstack IPv4/IPv6 endpoints.
Configure botocore to utilize dualstack IPv4/IPv6 endpoint for S3. This enables IPv6 only clients to use S3 through rohmu as well.

Use S3 dualstack endpoint by default

---

rohmu/object_storage/azure.py

This was trying to copy from the destination to the destination bucket.
Make it copy from the source to the destination.
Because trying to copy from the destination to the destination does not copy the data.

azure: fix inter-bucket copy not reading from the source bucket

---

rohmu/object_storage/azure.py
test/object_storage/test_azure.py

Due to how the Azure client works [here](https://github.com/Azure/azure-sdk-for-python/blob/azure-storage-blob_12.8.1/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L667) using a subclass of Enum for the `container_name` with AzureTransfer leads to confusing behaviour - the enum _key_ is used rather than the enum _value_ as would be expected. This fixes that behaviour.

azure: allow StrEnum use in AzureTransfer.get_or_create_container

---

.github/workflows/sphinx.yml

The checkout being in the main subdirectory, the pip install commands needs to
be adapted accordingly.
Fixes https://github.com/Aiven-Open/rohmu/pull/177

Fix failing Sphinx build due to inability to install dependencies

---

rohmu/object_storage/s3.py
test/object_storage/test_s3.py

This reduces memory by only loading large files like botocore/data/ec2/2016-11-15/service-2.json once. Currently these large files are being loaded every time a Transfer is created.

s3: share the session between transfers

---

rohmu/object_storage/google.py

replace dateutil with fromisoformat in google backend.
`dateutil.parser.parse` is particularly slow and covers a lot of use cases that are not relevant to parsing [RFC 3339 datetimes](https://googleapis.github.io/google-api-python-client/docs/dyn/storage_v1.objects.html#list).
This was bad enough that rohmu could eat >50% of CPU while listing entries from Google object storage.
(The next high CPU user is `json.decode`, but that's still far behind `dateutil` and harder to fix since it's inside `googleapiclient`.)

replace dateutil with fromisoformat in google backend

---

pyproject.toml
rohmu/common/models.py
rohmu/common/statsd.py
rohmu/delta/common.py
rohmu/object_storage/config.py
test/object_storage/test_azure.py
test/object_storage/test_s3.py
test/test_factory.py

This changes allows rohmu to use Pydantic V2 by making use of the `.v1` namespace.
It changes the requirements for pydantic to `pydantic >= 1.10.17`.
This should allow using rohmu with a code base that is in the process of moving from Pydantic V1 to V2 without disruptions.
This is the simplest implementation. Later on we can move to Pydantic V2 only.

Make rohmu compatible with Pydantic V2 using the .v1 namespace

---

rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/s3.py
test/object_storage/test_azure.py
test/object_storage/test_google.py
test/object_storage/test_s3.py
test/test_factory.py

GoogleTransfer objects create clients and never close the client, if we create many clients, we leak sockets.
Add a API to close a Transfer object and implement it in the GoogleTransfer subclass to close the google client.
Also implement it in Azure/S3 transfer objects for consistency (and hopefully one day we'll stop creating buckets during `__init__`, which will make the objects creation cheaper and free of side-effects.)
Because if we leak socket, then we eventually crash.

Close google/azure/s3 client when closing GoogleTransfer object [DDB-1160]

---

make_release.py
pyproject.toml

Fix the tooling to be able to make a release.
Because we can't make a release if the tools are broken.

Fix release tooling not working

---

rohmu/errors.py
rohmu/factory.py
rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
rohmu/transfer_pool.py
test/object_storage/test_google.py
test/test_factory.py

Introduce the `ensure_object_store_available` parameter to allow creating a transfer object without necessarily creating the backing resources.
When that flag is passed the constructor will not attempt to create missing resources (such as storage buckets), which would allow consumers of the API to handle error cases without having to expose exceptions from rohmu's implementation details.
Instead they can call `verify_object_storage` to check for existence/access, and/or `create_object_store_if_needed` to create the bucket/container if it doesn't already exist.
This provides a nicer interface to handle potential errors related to network issues/permission issues/etc outside of the constructor. It keeps the current behaviour by default for backwards compatibility.
It's a …

Handle deleted buckets gracefully

---

rohmu/object_storage/azure.py

The latest version of the azure-storage-blob package seems to have introduced some typing issues (most likely via https://github.com/Azure/azure-sdk-for-python/commit/cb47de53f3716757448343a2603e2f1e3feddc6d).
This PR solves this.
The version of `azure-storage-blob` is explicitly un-pinned in the `pyproject.toml` file, so it seems like a better option to address the typing issue rather than pin the package to an older version.
I opted for a warning log line instead of an assertion as that would at least provide some insight into what is happening. Theoretically, we might get in this situation even though the docs say we won't.

Fix Azure typing issues

---

rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
test/object_storage/test_object_storage.py

This adds a callback function in `copy_files_from`, which provides the transferred object key with completed and total files.
We want to measure the progress of transferred files. However measuring the amount of transferred bytes requires a provider based implementation. Therefore we measure the keys which is provider independent.

Add progress callback for transferred object keys in copy_files_from

---

rohmu/object_storage/azure.py
rohmu/object_storage/google.py
rohmu/object_storage/s3.py

S3 and Azure can throw IncompleteReadError when the TCP session was disrupted. However, current implementation does not re-reaise it as MaybeRecoverableError. As a result, programs like pghoard will give up basebackup download.
This is more likely to affect large (2~4 TiB) databases, because large database takes longer to download base backup and more likely to encounter at least one IncompleteReadError.
This commit re-reaise IncompleteReadError as MaybeRecoverableError, so pghoard can retry on an object without starting over.
I learned that pghoard use `MaybeRecoverableError` to decide whether it will retry or not. So I thought re-reaise IncompleteReadError as MaybeRecoverableError might be an option.

Re-reaise IncompleteReadError as MaybeRecoverableError

---

rohmu/object_storage/azure.py
rohmu/object_storage/base.py
rohmu/object_storage/google.py
rohmu/object_storage/local.py
rohmu/object_storage/s3.py
rohmu/object_storage/sftp.py
rohmu/object_storage/swift.py
test/object_storage/test_azure.py
test/object_storage/test_google.py
test/object_storage/test_local.py
test/object_storage/test_s3.py
test/object_storage/test_sftp.py
test/object_storage/test_swift.py

Most object storages support having a slash in the object
name and rohmu should be able to delete such objects.
Let the default behaviour the same but introduce an option
`preserve_trailing_slash` which allows to control whether the trailing
slash in the key are stripped or not.
Resolves: #198 
Introducing a new flag is backward compatible and preserves the existing behaviour in case this is actually a requirement for some user.
We can later on switch the default value of `preserve_trailing_slash` to `True` if we think we want this behaviour by default.
For local/sftp which can't support slashes I opted for explicitly raising an `Error` if the user passes `preserve_trailing_slash=True` instead of just ignoring the parameter.

Add option to preserve trailing slash on deletes

---

rohmu/object_storage/azure.py
rohmu/object_storage/google.py
test/object_storage/test_azure.py
test/object_storage/test_google.py

Batch multiple delete google API calls in a single HTTP request.
A single batch request is limited to 100 calls (recommended max batch size)
When we request more calls that that, we execute multiple batch requests.
Error handling
Any unsuccessful sub-request is retried before escalation (if status code is related to temporal errors).
[DDB-1246]

gcp: bulk request for gcp object storage deletion
